generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/explode-query
inputSpec: modules/openapi-generator/src/test/resources/3_0/snakecase-discriminator.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript
additionalProperties:
  platform: node
  npmName: '@openapitools/typescript-explode-query-petstore'
  projectName: typescript-explode-query-petstore
  moduleName: petstore