generatorName: typescript
outputDir: samples/openapi3/client/petstore/typescript/builds/object_params
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/typescript
additionalProperties:
  platform: node
  npmName: '@openapitools/typescript-node-object-parameters-petstore'
  useObjectParameters: true
  projectName: typescript-node-object-parameters-petstore
  moduleName: petstore
